config/routes.rb
Rails.application.routes.draw do  
  
  get 'articles/create'

  get 'articles/new'

  get 'articles/show'
  get 'articles/edit'

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def create
        params.permit!
        @article = Article.new(params[:article])
        @article.save #생성한 article모델 객체 저장
        redirect_to @article #방금 작성한 새 게시글 내용으로 자동 이동
    end
    
    def new
    end

    def index
        @articles=Article.all
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        params.permit!
        @article = Article.find(params[:id])
        @article.update(params[:article])
        redirect_to @article
    end

    def show
        @article = Article.find(params[:id])

    end
    def destroy
        article = Article.find(params[:id])
        article.destroy
        redirect_to articles_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%=form_for :article, url: article_path(@article), method: :patch do |f| %>
    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :content %> <br>
        <%= f.text_field :content %>
    </p>
    <p> <%= f.submit %> </p>
<% end %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.content %></td>
      <td><%= link_to 'show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for :article, url:'/articles/' do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %><br>
    </p>
    <p>
        <%= f.label :content %><br>
        <%= f.text_field :content %><br>
    </p>
    <p>
        <%=f.submit %>
    </p>
<%end%>

app/views/articles/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content: </strong>
  <%= @article.content %>
</p>
<%=link_to "수정", edit_article_path(@article)%>
<%=link_to "삭제", article_path(@article), method: :delete %>>
<%= link_to "전체 목록", articles_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>